[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("python3")'
hook_add = '''
	let g:deoplete#enable_at_startup = 1
	let g:deoplete#enable_smart_case = 1
	let g:deoplete#enable_ignore_case = 1
	imap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"
	imap <expr><s-tab> pumvisible() ? "\<c-p>" : "\<s-tab>"
	imap <expr><cr> pumvisible() ? deoplete#close_popup() : "\<cr>"
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
	let g:NERDTreeShowHidden = 1
	let g:NERDTreeShowBookmarks = 1
	nmap <silent><C-e> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
	let g:lightline = {
	\	'colorscheme': 'wombat',
	\}
'''

# LANGUAGE

[[plugins]] # HTML5
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]] # TOML
repo = 'cespare/vim-toml'
on_ft = 'toml'
